package evrentan.community.communitymanager.entity;

import lombok.*;

import javax.persistence.*;
import java.util.UUID;

/**
 * Community Entity Class represents the community table in the database.
 * It is represented by {@link evrentan.community.communitymanager.dto.Community} in DTO level.
 *
 * @author <a href="https://github.com/evrentan">Evren Tan</a>
 * @since 1.0.0
 */
@Entity
@Table(name = "community")
@Getter @Setter
@NoArgsConstructor
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@EqualsAndHashCode @ToString
@Builder
public class CommunityEntity {
    /**
     * Community ID in UUID Type.
     * It is equalized to the id column in the database.
     * It is the primary key of the table.
     * It is auto-generated by the database.
     * It is unique.
     * It is not nullable.
     *
     * @since 1.0.0
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private UUID id;

    /**
     * Community Name in String Type.
     * It is equalized to the name column in the database.
     *
     * @since 1.0.0
     */
    @Basic
    @Column(name = "name")
    private String name;

    /**
     * Community Description in String Type.
     * It is equalized to the description column in the database.
     *
     * @since 1.0.0
     */
    @Basic
    @Column(name = "description")
    private String description;

    /**
     * Indicates whether the community is active or not.
     * It is equalized to the is_active column in the database.
     *
     * @since 1.0.0
     */
    @Basic
    @Column(name = "is_active")
    private boolean active;
}