package evrentan.community.venuemanager.entity;

import lombok.*;

import javax.persistence.*;
import java.util.UUID;

/**
 * Room Entity Class represents the venue table in the database.
 * It is represented by {@link evrentan.community.venuemanager.dto.Room} in DTO level.
 *
 * @author <a href="https://github.com/evrentan">Evren Tan</a>
 * @since 1.0.0
 */
@Entity
@Table(name = "room")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@EqualsAndHashCode @ToString
@Builder
public class RoomEntity {
  /**
   * Room ID in UUID Type.
   * It is equalized to the id column in the database.
   * It is the primary key of the table.
   * It is auto-generated by the database.
   * It is unique.
   * It is not nullable.
   *
   * @since 1.0.0
   */
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Column(name = "id")
  private UUID id;

  /**
   * Room Name in String Type.
   * It is equalized to the name column in the database.
   *
   * @since 1.0.0
   */
  @Basic
  @Column(name = "name")
  private String name;

  /**
   * Room Description in String Type.
   * It is equalized to the description column in the database.
   *
   * @since 1.0.0
   */
  @Basic
  @Column(name = "description")
  private String description;

  /**
   * Room Capacity in Integer Type.
   * It is equalized to the capacity column in the database.
   *
   * @since 1.0.0
   */
  @Basic
  @Column(name = "capacity")
  private Integer capacity;

  /**
   * Venue ID that the Room is located in UUID Type.
   * It is equalized to the city venue_id in the database.
   *
   * @since 1.0.0
   */
  @Basic
  @Column(name = "venue_id")
  private UUID venueId;

  /**
   * Indicates whether the venue is active or not.
   * It is equalized to the is_active column in the database.
   *
   * @since 1.0.0
   */
  @Basic
  @Column(name = "is_active")
  private boolean active;
}