package evrentan.community.venuemanager.entity;

import evrentan.community.venuemanager.dto.entity.Venue;
import jakarta.persistence.*;
import lombok.*;

import java.util.UUID;

/**
 * Venue Entity Class represents the venue table in the database.
 * It is represented by {@link Venue} in DTO level.
 *
 * @author <a href="https://github.com/evrentan">Evren Tan</a>
 * @since 1.0.0
 */
@Entity
@Table(name = "venue")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@EqualsAndHashCode @ToString
@Builder
public class VenueEntity {
  /**
   * Venue ID in UUID Type.
   * It is equalized to the id column in the database.
   * It is the primary key of the table.
   * It is auto-generated by the database.
   * It is unique.
   * It is not nullable.
   *
   * @since 1.0.0
   */
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Column(name = "id")
  private UUID id;

  /**
   * Venue Name in String Type.
   * It is equalized to the name column in the database.
   *
   * @since 1.0.0
   */
  @Basic
  @Column(name = "name")
  private String name;

  /**
   * Venue Description in String Type.
   * It is equalized to the description column in the database.
   *
   * @since 1.0.0
   */
  @Basic
  @Column(name = "description")
  private String description;

  /**
   * Venue City in String Type.
   * It is equalized to the city column in the database.
   *
   * @since 1.0.0
   */
  @Basic
  @Column(name = "city")
  private String city;

  /**
   * Venue Address in String Type.
   * It is equalized to the address column in the database.
   *
   * @since 1.0.0
   */
  @Basic
  @Column(name = "address")
  private String address;

  /**
   * Indicates whether the venue is active or not.
   * It is equalized to the is_active column in the database.
   *
   * @since 1.0.0
   */
  @Basic
  @Column(name = "is_active")
  private boolean active;
}