package evrentan.community.venuemanager.entity;

import jakarta.persistence.*;
import lombok.*;

import java.util.UUID;

/**
 * VenueRoom Entity Class represents the venue_room table in the database.
 * It is represented by {@link evrentan.community.venuemanager.dto.VenueRoom} in DTO level.
 *
 * @author <a href="https://github.com/evrentan">Evren Tan</a>
 * @since 1.0.0
 */
@Entity
@Table(name = "venue_room")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@EqualsAndHashCode @ToString
@Builder
public class VenueRoomEntity {
  /**
   * Room ID in UUID Type.
   * It is equalized to the id column in the database.
   * It is the primary key of the table.
   * It is auto-generated by the database.
   * It is unique.
   * It is not nullable.
   *
   * @since 1.0.0
   */
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Column(name = "id")
  private UUID id;

  /**
   * Venue ID in UUID Type.
   * It is equalized to the venue_id column in the database.
   *
   * @since 1.0.0
   */
  @Basic
  @Column(name = "venue_id")
  private UUID venueId;

  /**
   * Room ID in UUID Type.
   * It is equalized to the room_id column in the database.
   *
   * @since 1.0.0
   */
  @Basic
  @Column(name = "room_id")
  private UUID roomId;

  /**
   * Indicates whether the venue room association is active or not.
   * It is equalized to the is_active column in the database.
   *
   * @since 1.0.0
   */
  @Basic
  @Column(name = "is_active")
  private boolean active;
}